# Generated by Django 4.0.3 on 2022-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_mail', models.EmailField(max_length=50)),
                ('user_phone', models.BigIntegerField()),
                ('user_address', models.CharField(max_length=50)),
                ('user_profile', models.ImageField(upload_to='images/')),
                ('password', models.CharField(help_text='Enter your Password', max_length=60, null=True)),
                ('regs_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
