# Generated by Django 4.0.3 on 2022-12-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('feedbk_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.IntegerField(help_text='data', null=True)),
                ('feedback1', models.IntegerField(help_text='feedback1', null=True)),
                ('feedback2', models.IntegerField(help_text='feedback2', null=True)),
                ('overreview', models.CharField(max_length=400, null=True)),
                ('sentiment', models.CharField(help_text='sentiment', max_length=60, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
