# Generated by Django 4.1.4 on 2022-12-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_feedbackmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="user_otp",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="user_otp_status",
            field=models.CharField(default="otp is pending", max_length=50),
        ),
    ]
