# Generated by Django 4.1.4 on 2022-12-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_usermodel_user_otp_usermodel_user_otp_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="onclick_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
