# Generated by Django 4.1.4 on 2022-12-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0005_alter_usermodel_onclick_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="onclick_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
